name: Restful-Booker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'oracle'

      - name: Tests run
        env:
          USERNAME: ${{secrets.USERNAME}}
          PASSWORD: ${{secrets.PASSWORD}}
          BASE_URI: ${{secrets.BASE_URI}}
        working-directory: Restful-booker
        run: mvn test
