name: Restful-Booker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      BOOKER_BASE_URI: ${{ secrets.BOOKER_BASE_URI }}
      BOOKER_USERNAME: ${{ secrets.BOOKER_USERNAME }}
      BOOKER_PASSWORD: ${{ secrets.BOOKER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'oracle'

      - name: Run tests
        working-directory: Restful-booker
        run: mvn test